config/routes.rb
Rails.application.routes.draw do
  root "tweets#index"
  devise_for :users
  resources :tweets, only: [:index, :show, :new, :create] 
  resources :users do
    resources :tweets do
      resources :likes
    end
  end

  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships,  only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user, dependent: :destroy

  validates :sentence, presence: true
  validates :sentence, length: { maximum: 140}
end

app/models/user.rb
class User < ApplicationRecord

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :name, length: { maximum: 30}

  validates :introduction, length: { maximum: 100}

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.create(tweet_id: params[:tweet_id])
    redirect_to tweet_path(params[:tweet_id])
  end

  def destroy
    @like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    @like.destroy
    redirect_to tweet_path(params[:tweet_id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @tweet.replies.create(reply_params)
    redirect_to tweet_path(@tweet)
  end

  private
    def reply_params
      params.require(:reply).permit(:sentence)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @user = current_user
    @tweets = Tweet.all.order(created_at: 'desc')
  end

  def show
    @user = current_user
    @tweet = Tweet.find(params[:id])
  end

  def new
    @user = current_user
    @tweet = @user.tweets.new
  end

  def create
    @user = current_user
    @tweet = @user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path
    else
      # render plain: @tweet.errors.inspect
      render "new"
    end
  end

  def destroy
    @user = Tweet.find(params[:id]).user
    
    if @user == current_user
      @tweet = @user.tweets.find(params[:id])
      @tweet.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private
    def tweet_params
      params.require(:tweet).permit(:sentence)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
    def user_params
      params.require(:user).permit(:name, :introduction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<div style="width: 75%; background-color:#00aced ; text-align: center; margin: 5px auto">
  <h1 style="color: white"><%= link_to "Twitterもどき", root_path, style:"color:white; text-decoration: none;" %></h1>
</div>

<div style="display: flex; width:75%; margin: 5px auto;">
  <div>
    <div style="text-align: center">
      @<%= @user.name %>
    </div>
    <div style="text-align: center">
      <%= link_to "Tweet", new_user_tweet_path(@user) %>
    </div>
    <div style="text-align: center">
      <%= link_to "Home", user_path(@user) %>
    </div>
    <div style="text-align: center">
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete%>
    </div>
  </div>

  <div style="text-align: center; width: 75%; margin: 10px auto;">
    <% @tweets.each do |tweet| %>
      <div style="padding: 5px;border: 2px solid #000000; margin-top: 5px">
        @<%=  tweet.user.name %><br>
        <%=  link_to tweet.sentence, tweet_path(tweet) %>
        <div style="margin-top: 10px">
          いいね <%= tweet.liked_users.count %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tweets/new.html.erb
<div style="width: 75%; background-color:#00aced ; text-align: center; margin: 5px auto">
  <h1 style="color: white"><%= link_to "Twitterもどき", root_path, style:"color:white; text-decoration: none;" %></h1>
</div>

<div style="display: flex; width:75%; margin: 5px auto;">
<div>
  <div style="text-align: center">
    <%= link_to "Tweet", new_user_tweet_path(@user) %>
  </div>
  <div style="text-align: center">
    <%= link_to "Home", user_path(@user) %>
  </div>
  <div style="text-align: center">
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, style: "color:white;"%>
  </div>
</div>

<div style="text-align: center;margin: 10px auto;">
  <%= form_for @tweet do |f| %>
  <p>
    <%= f.text_area :sentence, placeholder: 'Tweet', :size=>"60x20" %>
    <% if @tweet.errors.messages[:sentence].any? %>
      <span class="error"><%= @tweet.errors.messages[:sentence][0] %></span>
    <% end %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>
</div>
</div>

app/views/tweets/show.html.erb
<div style="width: 75%; background-color:#00aced ; text-align: center; margin: 5px auto">
  <h1 style="color: white"><%= link_to "Twitterもどき", root_path, style:"color:white; text-decoration: none;" %></h1>
</div>

<div style="display: flex; width:75%; margin: 5px auto;">
  <div style="margin: 5px auto;">
    <div style="text-align: center">
      @<%= @user.name %>
    </div>
    <div style="text-align: center;margin-top: 5px">
      <%= link_to "Tweet", new_user_tweet_path(@user) %>
    </div>
    <div style="text-align: center">
      <%= link_to "Home", user_path(@user) %>
    </div>
    <div style="text-align: center">
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete%>
    </div>
  </div>

  <div style="text-align: center; width:75%; margin: 10px auto">
    <div>
      <%= link_to @tweet.user.name, user_path(@tweet.user) %>
    </div>

    <div style="width: 75%; margin: 10px auto">
      <%= @tweet.sentence %>
    </div>
    <div>
        いいね<%= @tweet.liked_users.count %>
    </div>

    <% if current_user.already_liked?(@tweet) %>
      <%= button_to 'いいねを取り消す', user_tweet_like_path(@user, @tweet), method: :delete %>
    <% else %>
      <%= button_to 'いいね', user_tweet_likes_path(@user, @tweet), method: :post%>
    <% end %>
    <div>
      <%= link_to "Reply" %>
    </div>

    <h2>いいねしたユーザー</h2>
    <% @tweet.liked_users.each do |user| %>
      <li><%= link_to user.name, user_path(user)%></li>
    <% end %>
  </div>
  <div>
    <p>
      <% if current_user == @tweet.user %>
        <%= link_to "削除", user_tweet_path(@user,@tweet), method: :delete %>
      <% end %>
    </p>
  </div>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>  

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    フォロー中
  </a><br>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit User</h2>
<%= form_for @user, url: user_path(@user) do |f| %>
<p>
  <%= f.text_field :name, placeholder: 'enter name' %>
  <% if @user.errors.messages[:name].any? %>
  <span class="error"><%= @user.errors.messages[:name][0] %></span>
  <% end %>
</p>
<p>
  <%= f.text_field :introduction, placeholder: 'enter intro' %>
    <% if @user.errors.messages[:introduction].any? %>
    <span class="error"><%= @user.errors.messages[:introduction][0] %></span>
  <% end %>
  </p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div style="width: 75%; background-color:#00aced ; text-align: center; margin: 5px auto">
  <h1 style="color: white"><%= link_to "Twitterもどき", root_path, style:"color:white; text-decoration: none;" %></h1>
</div>

<div style="text-align: center;display: flex;width:75%; margin: 5px auto">
  <div style="margin: 5px auto;">
    <h3>@<%= @user.name %></h3>
    <h4>一言:<%=  @user.introduction %></h4>
    <p>ツイート<%= @user.tweets.count %></p>
  </div>
  <div>
  <p>
    <% if current_user == @user %>
      <%= link_to '変更', edit_user_path(@user) %>
    <% end %>
  </p>
  </div>
</div>

<div style="display: flex; width:75%; margin: 5px auto;">
  <div>
    <div style="text-align: center;margin-top: 5px">
      <%= link_to "Tweet", new_user_tweet_path(@user) %>
    </div>
    <div style="text-align: center">
      <%= link_to "Home", user_path(@user) %>
    </div>
    <div style="text-align: center">
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete%>
    </div>
    <div>
        <%= render 'follow_form' %>
        <%= render 'stats' %>
    </div>
  </div>

  <div style="text-align: center; width:75%; margin: 10px auto">

    <% @user.tweets.each do |tweet| %>
      <div style="height: 75px;border: 2px solid #000000; margin-top: 5px">
        <%=  tweet.user.name %><br>
        <%=  link_to tweet.sentence, tweet_path(tweet) %><br>
        いいね <%= tweet.liked_users.count %>
      </div>
      <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<div style="width: 75%; background-color:#00aced ; text-align: center; margin: 5px auto">
  <h1 style="color: white"><%= link_to "Twitterもどき", root_path, style:"color:white; text-decoration: none;" %></h1>
</div>
<h1>フォロー一覧</h1>

<div style= "margin: 10px auto; width:50%">
  <% @user.followings.each do |user| %>
     <div>
      　<%= link_to user.name, user_path(user) %>
     </div>
  <% end %>
</div>

app/views/users/show_follower.html.erb
<div style="width: 75%; background-color:#00aced ; text-align: center; margin: 5px auto">
   <h1 style="color: white"><%= link_to "Twitterもどき", root_path, style:"color:white; text-decoration: none;" %></h1>
</div>
<h1>フォロワー一覧</h1>
  
<div style= "margin: 10px auto; width:50%">
   <% @user.followers.each do |user| %>
      <div>
         <%= link_to user.name, user_path(user) %>
       </div>
   <% end %>
</div>
  